blank_issues_enabled: false
contact_links:
  - name: MeiliSearch Product Discussions
    url: https://github.com/meilisearch/product/discussions
    about: Share your feedback with the MeiliSearch team.
