contact_links:
  - name: MeiliSearch Product Discussions
    url: https://github.com/meilisearch/product/discussions/categories/feedback
    about: Please open a discussion rather than an issue to propose a feature or give feedback.
